section2

diff --git a/dockerfile1 b/dockerfile1
--- a/dockerfile1
+++ b/dockerfile1
@@ -55,7 +55,10 @@ docker pc # container test is no longer running
 --------------------------------------------------------------------------------------------------
 https://docs.google.com/document/d/1LsQyB_9DlKkA2CfFgF0zkRclfO9lZT9ZoIHcANWzvxQ/edit?usp=sharing
 --------------------------------------------------------------------------------------------------
-Section 2: image creation, management, and registry
+---------------------------------------------------
+---------------------------------------------------
+>>>>>>Section 2: image creation, management, and registry<<<<<<<<
+---------------------------------------------------
 ---------------------------------------------------
 dockerfile>>docker build>>dockerimage
 >>simple docker file
@@ -100,3 +103,131 @@ RUN apt install service
 EXPOSE 9324
 CMD ["service"]
 <!-- means this service will listening on port 9314  -->
+----------------------------------
+# healthcheck istruction docker allows us to tell the platform on how to test that our app is healthy
+HEALTHCHECK --interval=5m --timeout=3s \
+CMD curl -f http://localhost/ | exit 1
+example: 
+docker run -dt --name tmp --health-cmd "curl -f http://localhost" --health-interval=5s --health-retries=1 busybox sh  #means still healthy only for 5s
+# -f in curl for make a one line error not an HTML form
+# https://docs.docker.com/engine/reference/run/#healthcheck
+------------------------
+# the command from ENTRYPOINT cannot be appended like CMD command so i can't tell it ping -c it will give me error
+# CMD: Sets default parameters that can be overridden from the Docker command line interface (CLI) while running a docker container.
+# ENTRYPOINT: Sets default parameters that cannot be overridden while executing Docker containers with CLI parameters.
+# we can override ENTRYPOINT with a flag like --entrypoint [command] like docker run --entrypoint COMMAND containername
+# the WORKDIR sets the working directory for any RUN, CMD, ENTRYPOINT, COPY and ADD instructions that follow it in the dockerfile
+
+FROM busybox
+RUN mkdir /root/demo
+WORKDIR /root/demo
+RUN touch file1.txt 
+CMD ["/bin/sh"]
+------
+FROM busybox
+RUN mkdir -p /root/demo/context1/context2
+WORKDIR /root/demo
+WORKDIR context1
+WORKDIR context2
+RUN touch file01.txt
+CMD ["/bin/sh"]
+-------------
+# the ENV instructions sets the environment variable <key> to the value <value>
+ENV NGINX 1.2
+RUN curl -SL http://example.com/web-$NGINX.tar.xz   # the $NGINX will be replaced with nginx 1.2
+RUN tar -xzvf web-$NGINX.tar.xz                     # the $NGINX will be replaced with nginx 1.2
+# setting environment variable from CLI using -e or --env or --env-file 
+docker run --env VAR1=value1 --env VAR2=value2 ubuntu env | grep VAR
+
+# Using ENV in CLI:
+docker run -dt --name env02 --env USER=ADMINUSER busybox sh
+docker exec -it env02 sh
+echo $USER 
+-----------
+# to tag an image
+docker build -t demo:v1 .  #demo is the name, v1 is the tag
+# retag
+docker tag ubuntu:latest myubuntu:v1   #same image with 2 names and 2 tags
+------------------------------------------
+# it can be useful to commit a container's file changes or settings into a new image. by default the container being commited and its processes will be paused while the image is committed
+docker container commit CONTAINER-ID imagename   #or
+docker container commit busybox busybox-modified   # using commit to make a modified image from the image we already work inside its container
+# to spicify change in a commit 
+docker container commit --change='CMD ["ash"]' busybox  #change this image from sh command to ash command
+# supported instructions for change with commit
+CMD | ENTRYPOINT | ENV | EXPOSE | LABEL | ONBUILD | USER | VOLUME | WORKDIR
+------------------------------------------------------
+# to eliminate the layers of docker file
+FROM ubunto
+RUN dd if=/dev/zero of=/root/file1.txt bs=1M count=100 && rm -f /root/file1.txt
+RUN dd if=/dev/zero of=/root/file2.txt bs=1M count=100 && rm -f /root/file2.txt
+# when you make the layers more less, the performance will be more efficient
+-----------------
+docker image build  # build is the child command. it's the best practice
+# example of child commands --> build inspect history import load ls prune pull push rm save tag
+--------------
+docker image inspect nginx | grep hostname
+docker image inspect nginx --format='{{.Id}}'
+docker image inspect nginx --format='{{json .ContainerConfig}}'  #with json format
+--------------------
+# docker image prune command allows us to clean up unused images (image without tags and image not referenced by any container)
+docker image prune -y
+docker image prune -a -y  #remove images wihtout at least one container associated with them
+-----------------------------------------------
+# flattening docker images
+docker export myubuntu > myubuntudemo.tar
+cat myubuntudemo.tar | docker import - myubuntu:latest
+# now the myubuntu:latest is less in size than the old one
+----------------------------------------------------------------
+# to save an image for transfering it between hosts
+docker save busybox > busybox.tar
+docker load < busybox.tar   # we transfer .tar file then load it to return it to be an image
+-------------------------------
+# docker uses a layer cache to optimize the process of building docker images and make it faster 
+# if you build an image twice, the second build will be more faster because of caching in docker
+# if the cache cannot be used for a particular layer, all subsequent layers will not be loaded from the cache
+
+# Dockerfile
+FROM python:3.7-slim-buster
+COPY . .
+RUN pip install --quiet -r requirements.txt
+ENTRYPOINT ["python", "server.py"]
+
+# requirements.txt
+certifi==2018.8.24
+chardet==3.0.4
+Click==7.0
+cycler==0.10.0
+decorator==4.3.0
+defusedxml==0.5.0
+
+# Build Commands:
+docker build -t without-cache .
+docker build -t with-cache .
+-----------------------------------------
+https://docs.google.com/document/d/1n60n6MymydOjdXboqX1RCP-xklkjiJ-ClS2fjJTwsCY/edit?usp=sharing
+------------------------------------------------
+--------------------------------------------
+SECTION 3 networking
+---------------------------------------------
+----------------------------------------------
+# drivers of docker are bridge, host, overlay, macvlan, none
+# if config >>>> docker0 interface
+docker network ls
+# in the bridge network, the container that runs get the ip range of the bridge network
+docker inspect bridge
+docker container run -dt --name myhost --network host ubuntu
+docker network inspect host
+# a bridge network uses a software bridge which allows containers connected to the same bridge network to communicate, 
+# while providing isolation from containers which are not connected to that bridge netowrk
+# bridge is the defautl network driver for docker
+-------------------------
+yum whatprovides brctl 
+brctl show   #show bridge networks
+yum install bridge-utils
+# i will skip parts of this sections because they are replaced now with K8s in prod
+-----------------------------------------------------------------------------------------------
+docker network create --driver bridge mybridge
+docker container run -dt --name mybridge01 --network mybridge ubuntu
+brctl show
+------------------
